services:
  - type: web
    name: sofiacash-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "7940060404"  
      - key: PORT
        value: "8000"
    plan: free
    healthCheckPath: /health
